### ISSUE TITLE
Query about the ventricle segmentation model

### ISSUE THREAD

**Issue by WangMengxiao319** [lileitech/MI_inverse_inference#1]
Dear Dr. Li，

Thanks for open-sourcing and sharing this insightful method. I have a few questions regarding the **deep learning-based ventricle segmentation model mentioned in the paper**. Could you please provide more details about which specific model was used? If possible, it would be greatly appreciated if you could share the code related to this part of the work, and even better if the model weights could be provided as well.

Thank you again for your time and contributions！

**Comment by lileitech** [comment]
Hi Mengxiao,

It is based on a open-source code from Dr Wenjia Bai. Here is the github link for this part of code: https://github.com/baiwenjia/ukbb_cardiac. Hope this information is helpful.

Kind regards,
Lei

**Comment by WangMengxiao319** [comment]
> Hi Mengxiao,
> 
> It is based on a open-source code from Dr Wenjia Bai. Here is the github link for this part of code: https://github.com/baiwenjia/ukbb_cardiac. Hope this information is helpful.
> 
> Kind regards, Lei

Thanks a lot!
